name: CI

on:
  push:
  pull_request:
  watch:
    types: [ started ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - uses: coursier/setup-action@v1
      #with:
        #jvm: adopt:11
        #apps: bloop

    - name: sbt Pass
      run: sbt 'testOnly FooTester -- -Dkey=Hello'

    - name: bloop
      run: |
        #sbt bloopInstall
        cs install bloop --only-prebuilt=true
        bloop test bloop-test -o FooTest -- -J-Dkey=Hello
