name: CI

on:
  push:
  pull_request:
  watch:
    types: [ started ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - uses: coursier/setup-action@v1
      with:
        apps: bloop:1.4.0

    - name: sbt Pass
      run: sbt 'testOnly FooTester -- -Dkey=Hello -Duser.key=Hellooooo'

    - name: bloop
      run: |
        sbt bloopInstall
        bloop test foo -o FooTester --verbose -- -J-Dkey=Hello -J-Duser.key=Hellooooo
